workflows:
  android-workflow:
    name: WeLoop Android
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli eas-cli
          npm install
      - name: Prebuild Android
        script: |
          npx expo prebuild --platform android --no-install --non-interactive
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
